// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run CCustomCmdTestPublishStartupMode tests

LOAD_SUITE tunitcustcmd_server

START_TESTCASE 			DEVSRVS-SSREFPLUGINS-CUSTCMD-0022
//! @SYMTestCaseID 		DEVSRVS-SSREFPLUGINS-CUSTCMD-0022
//! @SYMPREQ 			PREQ1871
//! @SYMTestType		UT
//! @SYMTestPriority		High
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Tests the behaviour of CCustomCmdPublishStartupMode.
//! 				Tests the cancel behaviour of CCustomCmdPublishStartupMode.
//! @SYMTestActions		doTestCreateExecuteAndDestroyL() The test performs operations on a CCustomCmdPublishStartupMode object, namely calling the following methods:
//! 					1.	NewL - Creating the object
//! 					2.	Initialize - Initialising the custom cmd
//! 					3.	Execute - Executing the custom cmd
//! 					4.  	Close - Closes the custom command
//! 				doTestFactoryCreateAndExecuteCancelL() The test performs operations on a CCustomCmdPublishStartupMode object, namely calling the following methods:
//! 					1.	SsmCustomCmdFactory::CmdPublishStartupModeNewL - Creating the object
//! 					2.	Initialize - Initialising the custom cmd
//! 					3.	Execute - Executing the custom cmd
//! 					4.  	ExecuteCancel - Cancels the custom command
//! 					5.  	Close - Closes the custom command
//! @SYMTestExpectedResults 	Command should execute normally and should complete with KErrNone.
RUN_TEST_STEP 100 tunitcustcmd_server CCustomCmdTestPublishStartupMode
END_TESTCASE 			DEVSRVS-SSREFPLUGINS-CUSTCMD-0022

