// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run GsaStateTranFromShutdownStep tests

LOAD_SUITE tgsa_i_server

START_TESTCASE 				DEVSRVS-SSPLUGINS-GSA-0033
//! @SYMTestCaseID  			DEVSRVS-SSPLUGINS-GSA-0033
//! @SYMDEF				DEF119568
//! @SYMTestCaseDesc			Checks for state transitions to fail and shutdown states from normal state 
//! 					under different scenarios.
//! @SYMTestType			CIT	
//! @SYMTestPriority			Critical
//! @SYMTestActions			Test checks the results for request state transition under different scenarios:		
//! 					1. Normal state to Shutdown state and then to Fail state.
//! 					Scenario 1 - Request for state change from Normal to shutdown state to critical substate
//! 					Cancel the request immediately
//!					Scenario 2 - Request for state change from Normal to shutdown state to any substate
//! 					Cancel the request immediately, so that we can proceed with the next test scenario.
//! 					Scenario 3 - Request for three state changes(1. shutdown state 2. invalid state 3. fail state) one after the other 
//! 					 i.e., second request is issued once first one is completed and the third one is issued after the second request is completed.
//! 					 Cancel the third request.
//! 					Scenario 4 - The system is now in shutdown state, request for state transition to normal state.
//! 					Scenario 5 - The system is now in shutdown state, request for state transition to fail state.						
//! @SYMTestExpectedResults 	
//! 					1. Normal state to Shutdown state and then to Fail state.
//! 					Scenario 1 - Request will be completed with KErrCancel
//! 					Scenario 2 - Request will be completed with KErrCancel
//! 					Scenario 3 - First request will completed with KErrNone 
//! 					Second request will completed with KErrNotSupported
//! 					Third request will completed with KErrCancel
//! 					Scenario 4 - Request will be completed with KErrNotSupported
//! 					Scenario 5 - Request will be completed with KErrNone
RUN_TEST_STEP 100 tgsa_i_server GsaStateTranFromShutdownStep
END_TESTCASE 				DEVSRVS-SSPLUGINS-GSA-0033
