// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run GsaStateTranFromStartupStep tests

LOAD_SUITE tgsa_i_server

START_TESTCASE 				DEVSRVS-SSPLUGINS-GSA-0036
//! @SYMTestCaseID  			DEVSRVS-SSPLUGINS-GSA-0036
//! @SYMDEF				DEF130922
//! @SYMTestCaseDesc			Checks for state transitions to shutdown states from Startup state 
//! 					under different scenarios.
//! @SYMTestType			CIT	
//! @SYMTestPriority			Critical
//! @SYMTestActions			Test checks the result for request state transition from Startup to Shutdown Critical State
//! 					1. Startup state to Shutdown state.
//! 					Scenario 1 - Request for state change from Startup to critical state
//! @SYMTestExpectedResults 		1. Startup state to Shutdown state.
//! 					Scenario 1 - Request will completed with KErrNone
RUN_TEST_STEP 100 tgsa_i_server GsaStateTranFromStartuptoShutdownStep
END_TESTCASE 				DEVSRVS-SSPLUGINS-GSA-0036
