// Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: Testing for Transition Monitoring feature implemented as part of Staged Shutdown REQ for AppCentric architecture. This feature allows clients to defer acknowledgement to state change notifications during shutdown.
//

//!		@file			
//!		@SYMTestSuiteName		DVS-SSMA-CMN-0014
//!		@SYMScriptTestEnvironment   	Details as in below:-
//!								1. testexecute framework(TEF3.0).
//!								For the testing purpose define macro TEST_SSM_GRACEFUL_SHUTDOWN(For power off request feature) and SYMBIAN_INCLUDE_APP_CENTRIC(for transition monitoring feature).
//!								Note: The system is going to be in shutdown state after executing this test and can not be restored to normal for executing other tests.
//!								So this test has to be executed separately or at the end on overnight build machines. 
//!		@SYMScriptPurpose		Test whether deferring a client more than the no. of times allowed returns an appropriate error.
//!		@SYMScriptCreationDate		18/08/2010

LOAD_SUITE  tcmn_transitionmonitor

START_TESTCASE			DVS-SSMA-CMN-0014
//! @SYMTestCaseID		DVS-SSMA-CMN-0014
//! @SYMPREQ 			SUB 405-5490
//! @SYMTestType		CIT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Test the behaviour of a server which defers more than the number of times a server is allowed to defer acknowledgement
//! @SYMTestActions		1.Create a thread and connect to the server with a domain Id and request for shutdown state change notification  
//!				2.Request state change to ESsmShutdown
//!				3.Defer acknowledgement twice, upon receiving state change notification to shutdown state, each time waiting for the previous defer call to complete before calling again
//! @SYMTestExpectedResults 	The second call to defer returns with KErrNotSupported
		
START_TEST_BLOCK  100	tcmn_transitionmonitor	z:\ssmatest\ssmatest_cmn_transitionmonitor.ini
	CREATE_OBJECT	RSsmStateAwareSession1  RSsmStateAwareSession1	
	CREATE_OBJECT   RSsmStateManager	RSsmStateManager
	COMMAND		RSsmStateAwareSession1	NewL
	COMMAND		RSsmStateManager	NewL
	COMMAND		RSsmStateAwareSession1	Connect	 			Domain
	COMMAND		RSsmStateManager	Connect
	COMMAND		RSsmStateAwareSession1	ReadIniData			MaxDefer
	COMMAND		!AsyncError=-5		RSsmStateAwareSession1		RequestStateNotification
	COMMAND		RSsmStateManager	RequestStateTransition  	ShutdownTransitionCriticalSubState
	OUTSTANDING
	COMMAND		RSsmStateAwareSession1	ReturnCount			MaxDefer
	COMMAND		RSsmStateAwareSession1	Close
	COMMAND		RSsmStateManager	Close
	COMMAND		RSsmStateAwareSession1	~
	COMMAND		RSsmStateManager	~
END_TEST_BLOCK	
END_TESTCASE			DVS-SSMA-CMN-0014
