// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run SSM SIM Status Observer tests

PRINT Swapping SID over to CSsmUiSpecific::StartupPSUid()
RUN_PROGRAM -1 setcap tclayer_server.exe 0 -SID 2000e65e tclayer_serverSID.exe
LOAD_SUITE tclayer_serverSID

START_TESTCASE 			DEVSRVS-SSREFPLUGINS-CLAYER-0023
//! @SYMTestCaseID 		DEVSRVS-SSREFPLUGINS-CLAYER-0023
//! @SYMPREQ 			PREQ1871
//! @SYMREQ			REQ9152
//! @SYMTestType		UT
//! @SYMTestPriority		Critical
//! @SYMTestStatus 		Implemented
//! @SYMTestCaseDesc		Check behaviour of creation and destruction of the SSM SIM status observer class
//! 				Check behaviour of SIM changed and SIM owned in the SSM SIM status observer class and custom command
//! 				Check behaviour of creation and destruction of the SSM SIM status observer class
//! @SYMTestActions		doTestInitalizationAndDestructionL() Tests that creation and destruction of the SSM SIM status observer class happens cleanly.
//! 				doTestSimChangedAndOwnedL() Tests that different values of change and owned are published correctly.
//! 				doTestSimEventsL() Tests that creation and destruction of the SSM SIM status observer class happens cleanly.
//! @SYMTestExpectedResults 	All methods handle the object data appropriately, with no errors reported and there
//! 					are no panics.
//! 				All methods handle the publish the data correctly, with no errors reported and there
//! 					are no panics.
//! 				All methods handle the object data appropriately, with no errors reported and there
//! 					are no panics.
RUN_TEST_STEP 100 tclayer_serverSID CCLayerTestSsmSimStatusObserver
END_TESTCASE 			DEVSRVS-SSREFPLUGINS-CLAYER-0023

